export interface PodcastItem {
    url: string;
    title: string;
    published: string;
    id: string;
}

const podcastsList: PodcastItem[] = [
    {
        url: "https://mcdn.podbean.com/mf/web/hqcvsi/ep_51_audio.mp3",
        title: "ההייטק מצמיח עסקים שעוזרים למצוא עבודה מהר יותר",
        published: "Fri, 01 Apr 2022 15:07:12 +0300",
        id: "podcast-0",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/ruscgy/ep_50_audio.mp3",
        title: "להמציא את עצמך בפיתוח מחדש! ויש הרבה דרכים לעשות את זה...",
        published: "Thu, 31 Mar 2022 15:16:32 +0300",
        id: "podcast-1",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/nm737j/ojt_7_ep_49_audio.mp3",
        title: "איך מסבירים בצוות על סטטוס משימות וצימוד עבודה ליעול הפיתוח | OJT Class | שיעור 7",
        published: "Tue, 22 Mar 2022 21:22:29 +0300",
        id: "podcast-2",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/dsah7u/audio_ep_48.mp3",
        title: "מפצחים קורות חיים של ג׳וניורים בשיתוף עם #כולא_לייק ושחר פולק",
        published: "Mon, 21 Mar 2022 13:33:46 +0300",
        id: "podcast-3",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/r6yzeq/ojt_6_ep_47_audio.mp3",
        title: "לקיחת אחריות והבנה של דוקומנטציה הן מפתח להצלחה בצוות פיתוח | OJT Class | שיעור 6",
        published: "Fri, 18 Mar 2022 10:10:43 +0300",
        id: "podcast-4",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/j3xyvz/audio_46_ojt_5.mp3",
        title: "צריך מוטיבציה בשביל לפתח | OJT Class | שיעור 5",
        published: "Mon, 14 Mar 2022 22:38:19 +0300",
        id: "podcast-5",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/m4vch9/audio_ep_45_ojt_4.mp3",
        title: "איך כותבים מסמך משימות פיתוח טכני לפני שפותחים טיקטים בלוח העבודה | OJT Class | שיעור 4",
        published: "Tue, 08 Mar 2022 12:57:55 +0200",
        id: "podcast-6",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/gmxwhb/ep_44_audio.mp3",
        title: "גיט פלואו ואיך עובדים בצוות עם ריאקט סטוריבוק, שמירת סדר של קוד ולבחור בין וונילה או ריאקט",
        published: "Wed, 02 Mar 2022 22:04:47 +0200",
        id: "podcast-7",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/y2tyhw/ep_43_ojt_3_audio_better.mp3",
        title: "עבודת צוות עם לוח משימות, קיקאוף לפרויקט וחשיבה על משימות טכניות | OJT Class | שיעור 3",
        published: "Tue, 01 Mar 2022 22:01:38 +0200",
        id: "podcast-8",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/jucvew/imovie_ojt_lesson_2_audio.mp3",
        title: "איכות סאונד בינונית 🙏 בוחרים טכנולוגיה מתאימה וקיקאוף לפרויקט שנעבוד עליו כצוות פיתוח | Coderz Live! OJT Class | שיעור 2",
        published: "Mon, 28 Feb 2022 22:46:46 +0200",
        id: "podcast-9",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/hznk8a/audio_41.mp3",
        title: "Raw Data!!! למה צריך אנליסטים בהייטק?",
        published: "Sun, 20 Feb 2022 18:29:33 +0200",
        id: "podcast-10",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/9g6fke/audio_40.mp3",
        title: "Coderz Live! OJT Class | מה צריך ללמוד בשביל להתחיל לעבוד בפיתוח מהיום הראשון בעבודה",
        published: "Thu, 17 Feb 2022 22:08:21 +0200",
        id: "podcast-11",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/gd7xwz/39.mp3",
        title: "Coderz Live! איך מושכים חברות אליכם בחיפוש עבודה בהייטק?",
        published: "Thu, 17 Feb 2022 07:58:11 +0200",
        id: "podcast-12",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/rpuzys/audio_38.mp3",
        title: "Coderz Live! למה מרגישים מתחזים בתהליך ראיונות עבודה",
        published: "Mon, 14 Feb 2022 22:29:49 +0200",
        id: "podcast-13",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/2vv23w/ep_37_audio.mp3",
        title: "פריימוורקים פינקו את מתפתחי הפרונט יותר מידי? דיון בעקבות פוסט שנוי במחלוקת",
        published: "Thu, 27 Jan 2022 22:39:34 +0200",
        id: "podcast-14",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/wjada8/audio_ep_36_increase.mp3",
        title: "לכתוב טסטים לאפליקציות מונע חרדות ותורם לשינה רציפה, תלמדו משי רזניק איך עושים את זה",
        published: "Thu, 20 Jan 2022 19:12:06 +0200",
        id: "podcast-15",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/krt5sr/audio_35.mp3",
        title: "DevOps, מזה? מיזה? מהם עושים? ומתי צריך אותם?",
        published: "Tue, 18 Jan 2022 20:28:05 +0200",
        id: "podcast-16",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/bv7xcb/34_audio.mp3",
        title: "הדרך הכי טובה להצליח בפיתוח בהייטק הישראלי היא להיכשל וללמוד מזה, ולמה נטאפ חברה מעולה לעבוד בה.",
        published: "Thu, 06 Jan 2022 17:13:24 +0200",
        id: "podcast-17",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/a836tm/33_audio.mp3",
        title: "איך להתבלט בפיתוח בהייטק ע״י העברת הרצאות, כתיבת מאמרים, ונוודות דיגיטלית ב-2022",
        published: "Sun, 02 Jan 2022 19:49:11 +0200",
        id: "podcast-18",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/3ms6dj/ep_32_audio.mp3",
        title: "איך להתמודד עם אנשים שאנחנו לא סובלים במקום העבודה ולגשר על פערים אישיים בצוות פיתוח",
        published: "Thu, 30 Dec 2021 09:14:06 +0200",
        id: "podcast-19",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/tyue36/31_audio.mp3",
        title: "קהילת #כולא_לייק עוזרת להיכנס להייטק, ואיך הופכים שירות של עירייה לחכם יותר",
        published: "Tue, 28 Dec 2021 21:32:30 +0200",
        id: "podcast-20",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/rdjntj/ana_ep_30_audio.mp3",
        title: "אנה מספרת איך קודרז עזרה והדריכה אותה להתקבל למשרה ראשונה בפיתוח בהייטק",
        published: "Thu, 23 Dec 2021 17:35:21 +0200",
        id: "podcast-21",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/zzxpi6/ep_29_audio.mp3",
        title: "כל מה שטוב בפיתוח פולסטאק בימינו",
        published: "Tue, 21 Dec 2021 13:47:33 +0200",
        id: "podcast-22",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/bcwmy4/rendered_28_audio.mp3",
        title: "פיתוח אפליקצייה לקודרז בשבועיים? תכנון, ניהול מוצר, כתיבת קוד, ניהול זמנים, בדיקות, עיצוב וחוסר שינה",
        published: "Wed, 15 Dec 2021 17:00:36 +0200",
        id: "podcast-23",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/87d7mw/ep_27_audio.mp3",
        title: "חיזוקים וטיפים למתראיינים במשרות פיתוח בהייטק",
        published: "Thu, 02 Dec 2021 21:06:54 +0200",
        id: "podcast-24",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/32upge/ep_26_audio.mp3",
        title: "פרדוקס גיוס ג׳וניורים בהייטק | ואיך יוצאים מהלופ הזה?",
        published: "Wed, 01 Dec 2021 18:48:43 +0200",
        id: "podcast-25",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/t9ry66/ep_25_final_audio.mp3",
        title: "מיקרוסרביסים או מונוליט? יתרונות וחסרונות ומה צריך לבחור כשמתחילים פרויקט חדש",
        published: "Tue, 30 Nov 2021 23:21:57 +0200",
        id: "podcast-26",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/eynxfq/oz_ovadioa_audio.mp3",
        title: "איך להבין את הלא מובן מראש כשמחפשים משרות פיתוח כג׳וניורים/ות",
        published: "Sat, 27 Nov 2021 20:33:19 +0200",
        id: "podcast-27",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/sh858j/agile_scrum_audio.mp3",
        title: "איך צוות פיתוח עובד בחברת הייטק? | מדריך מקיף על עולם ה- Agile וה- Scrum | מדריך למתחילים ומתקדמים",
        published: "Fri, 26 Nov 2021 17:07:52 +0200",
        id: "podcast-28",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/de9v59/ep_22_audio.mp3",
        title: "שני כהן מפתחת צד שרת מסבירה למה צריך להעיז ולאתגר את עצמך כל פעם מחדש עם קוד",
        published: "Thu, 25 Nov 2021 09:17:35 +0200",
        id: "podcast-29",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/3j2kb6/podcast_21.mp3",
        title: "הסיפור שלה בהייטק; מתארחת: ליטל שלו, מנהלת פיתוח",
        published: "Tue, 23 Nov 2021 22:13:50 +0200",
        id: "podcast-30",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/nbmfpp/ep_208ozsi.mp3",
        title: "הקשר הבלתי נראה בין מחלקת פיתוח למחלקת השיווק וכלים להזנקת הקריירה | מתארח: תום אורבך",
        published: "Mon, 22 Nov 2021 17:19:12 +0200",
        id: "podcast-31",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/9mj52f/Audio_finallllll_contract_render_resized.mp3",
        title: "מה עושים כשמקבלים חוזה? ניהול משא ומתן והתמקחות ומה באמת חשוב לדעת",
        published: "Fri, 19 Nov 2021 17:00:31 +0200",
        id: "podcast-32",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/ikvpnt/npm_audio.mp3",
        title: "מדריך NPM ופרסום חבילות 📦",
        published: "Tue, 16 Nov 2021 01:35:54 +0200",
        id: "podcast-33",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/uu8dzi/backend_01_audio.mp3",
        title: "הקדמה לפיתוח צד שרת | מדריך למתחילים",
        published: "Wed, 10 Nov 2021 23:11:19 +0200",
        id: "podcast-34",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/jr47kh/adir_kendel_ep_16_trick_q_in_interview_audio.mp3",
        title: "שאלות מכשילות בראיונות עבודה של משרות פיתוח | טיפים איך לשרוד ראיון ולעבור אותו",
        published: "Tue, 09 Nov 2021 22:46:14 +0200",
        id: "podcast-35",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/wk7uyi/shahar_polak_podcast_audio_mp3.mp3",
        title: "לעבוד במשרת פיתוח דרוש הרבה יותר מלכתוב קוד",
        published: "Tue, 09 Nov 2021 17:47:25 +0200",
        id: "podcast-36",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/h8jqs4/cover_letter_with_cv.mp3",
        title: "מכתב מקדים עם שליחת קורות חיים למשרות פיתוח | מדריך חשוב ליישום כשמחפשים עבודה",
        published: "Mon, 08 Nov 2021 11:27:56 +0200",
        id: "podcast-37",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/mzesmn/react_router_v5_to_v6_audio.mp3",
        title: "עידכון ל- react router dom לגרסה v6 | מדריך שדרוג",
        published: "Sun, 07 Nov 2021 23:13:54 +0200",
        id: "podcast-38",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/yjsr6e/ep_12_full_audio.mp3",
        title: "למה מתכנתים/ות לא משתמשים בכלי הכי חשוב? ואופטימיזציה נכונה לאפליקציות שלנו ברשת",
        published: "Wed, 03 Nov 2021 22:58:25 +0300",
        id: "podcast-39",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/r5cnee/full_audio.mp3",
        title: "?איך מנהלים מתמודדים עם בחירה של מועמד/ת למשרת פיתוח ומה צריך ללמוד מזה",
        published: "Tue, 02 Nov 2021 16:25:59 +0300",
        id: "podcast-40",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/5wv8bi/coderz_podcast_10_yair_choen_podcast.mp3",
        title: "להיות מפתח ווב בגיל 22 והאתגרים שאפשר להתגבר עליהם",
        published: "Thu, 28 Oct 2021 11:54:52 +0300",
        id: "podcast-41",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/gwymjf/get_hired_as_a_developer.m4a",
        title: "כיצד להתקבל למשרת פיתוח בהייטק? | מדריך וטיפים שיעזרו",
        published: "Tue, 26 Oct 2021 17:11:52 +0300",
        id: "podcast-42",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/iis4z3/how_the_internet_works.mp3",
        title: "שאלה מראיונות פיתוח שתמיד שוכחים, איך האינטרנט עובד?",
        published: "Sun, 24 Oct 2021 16:17:53 +0300",
        id: "podcast-43",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/nwq3c8/imposter_syndrome_rendered.mp3",
        title: "אני מרגיש מתחזה בראיון או בעבודה כמתכנת, למה? תסמונת המתחזה ואיך להתגבר עליה",
        published: "Sun, 24 Oct 2021 16:14:50 +0300",
        id: "podcast-44",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/skirqr/frontend_roadmap_part_2.mp3",
        title: "מסלול וטכנולוגיות שצריך ללמוד | חלק 2 מתוך 2 | Frontend Development",
        published: "Sun, 24 Oct 2021 15:09:25 +0300",
        id: "podcast-45",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/tvq8zf/frontend_roadmap_part_1.mp3",
        title: "מסלול וטכנולוגיות שצריך ללמוד | חלק 1 מתוך 2 | Frontend Development",
        published: "Sun, 24 Oct 2021 14:55:40 +0300",
        id: "podcast-46",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/w5bzh2/backend_roadmap_part_2.mp3",
        title: "מסלול וטכנולוגיות שצריך ללמוד | חלק 2 מתוך 2 | Backend Development",
        published: "Sun, 24 Oct 2021 14:54:06 +0300",
        id: "podcast-47",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/ti73bv/backend_roadmap_part_1.mp3",
        title: "מסלול וטכנולוגיות שצריך ללמוד | חלק 1 מתוך 2 | Backend Development",
        published: "Sun, 24 Oct 2021 14:50:23 +0300",
        id: "podcast-48",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/fiyive/episode_4.mp3",
        title: "קודבוקס ואיך זה קשור למפתחים ג׳וניורים",
        published: "Thu, 21 Oct 2021 13:11:10 +0300",
        id: "podcast-49",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/8y95jt/episode_3.mp3",
        title: "החלקים החשובים שאולי פיספסתם בעיצוב לווב",
        published: "Thu, 21 Oct 2021 13:09:47 +0300",
        id: "podcast-50",
    },
    {
        url: "https://mcdn.podbean.com/mf/web/5qju7w/podcast_2_audio.mp3",
        title: "איזה פריימוורק להתחיל? Angular, React, Vue?",
        published: "Thu, 21 Oct 2021 13:04:03 +0300",
        id: "podcast-51",
    },
];

export default podcastsList;
